### ISSUE TITLE
 Didn't find class "lib.android.paypal.com.magnessdk.MagnesSource"

### ISSUE THREAD

**Issue by rathoddeepak** [ekreative/react-native-paypal#7]
implementation ('com.paypal.checkout:android-sdk:1.1.0') {
    exclude group: 'com.paypal.android.sdk', module: 'data-collector'
  }
  
  their is an issue with the library
  
    implementation ('com.paypal.checkout:android-sdk:1.1.0') 
    
    remove that exclude part it will work
    
    and make sure to add value for returnUrl

**Comment by vasylnahuliak** [comment]
@rathoddeepak Could you create the GitHub repository with an example? Also, could you please add information about your environment `npx react-native info`

**Comment by rathoddeepak** [comment]
@vasylnahuliak yes sure 


Will update here we done

**Comment by vasylnahuliak** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
