### ISSUE TITLE
how to pass request object

### ISSUE THREAD

**Issue by rsjaiswal181** [ekreative/react-native-paypal#8]
provide a example of this library in which request object also passed it
because i got a error on it

[Error: The user cancelled]

**Comment by vasylnahuliak** [comment]
You can understand arguments from types https://github.com/ekreative/react-native-paypal/blob/master/index.d.ts

```typescript
import { getBundleId } from 'react-native-device-info'; // for the temporary solution you can ignore this and use a hardcoded string in the returnUrl

const approvalData = await Paypal.startWithOrderId({
  clientId: 'PAYPAL_CLIENT_ID', // in general pass from environment variables
  useSandbox: true, // "false" for production
  orderId: 'orderId', // pass orderId from your backend
  returnUrl: `${getBundleId()}://paypalpay`, // you need setup this in PayPal settings
});
```

Also, this information is available in the documentation https://github.com/ekreative/react-native-paypal#usage

**Comment by vasylnahuliak** [comment]
Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
